### PR TITLE
Fix out of bounds for get and set functions in dynamicarrays

### LINKED ISSUE #113: Add boundary checks in  get/set methods of DyanmicArray class.

### PR DESCRIPTION
**Pull request by GodisC00L**
Fixes #113 
-----------------
Fixed out of bounds for get and set functions.
Added relevant test for the fix

### CODE REVIEW

File: src/test/java/com/williamfiset/algorithms/datastructures/dynamicarray/DynamicArrayTest.java [hunk 1]
```diff
@@ -50,6 +50,48 @@ public void testIndexOutOfBounds4() {
     list.removeAt(-66);
   }
 
+  @Test(expected = Exception.class)
```
Comment (williamfiset) [inline src/test/java/com/williamfiset/algorithms/datastructures/dynamicarray/DynamicArrayTest.java]: Probably best to check that the exception is IndexOutOfBoundsException rather than the generic Exception

Comment (GodisC00L) [reply src/test/java/com/williamfiset/algorithms/datastructures/dynamicarray/DynamicArrayTest.java]: Fixed as requested :)

**Comment by williamfiset** [comment]
Thanks :)
